{% set version = "1.1.8.3" %}

package:
  name: simupop
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simuPOP/simuPOP-{{ version }}.tar.gz
  sha256: 85048965ab6f1515deacf824d9a23d5549deb481a3ab33c02ccc6ef1c4dbe1f3

build:
  number: 1000
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - zlib
    - swig
  run:
    - python
    - zlib

test:
  imports:
    - simuPOP
    - simuOpt

about:
  home: http://github.com/BoPeng/simuPOP
  license: GPL3
  license_family: GPL
  license_file: COPYING
  summary: 'A general-purpose forward-time population genetics simulation environment'
  description: |
    simuPOP is a forward-time population genetics simulation environment. The
    core of simuPOP is a scripting language (Python) that provides a large
    number of objects and functions to manipulate populations, and a mechanism
    to evolve populations forward in time. Using this R/Splus-like environment,
    users can create, manipulate and evolve populations interactively, or write
    a script and run it as a batch file. Owing to its flexible and extensible design,
    simuPOP can simulate large and complex evolutionary processes with ease. At
    a more user-friendly level, simuPOP provides an increasing number of built-in
    scripts that perform simulations ranging from implementation of basic population
    genetics models to generating datasets under complex evolutionary scenarios.
  doc_url: http://simuPOP.sourceforge.net/Main/Documentation
  dev_url: https://github.com/BoPeng/simuPOP

extra:
  recipe-maintainers:
    - BoPeng
