travis:
  secure:
    BINSTAR_TOKEN: LBFnCd63031dKIjY05RDSzQt+bAtCrhu/mnOp0k67FeRbkNR5jSzZh1C48a2GTXMPNfglLsa9iIYJm5WtWPLSyS3UT9zyvr5SwnCHnuGP33LHhWFHWuRNC0ire1icFrSjwHbOnTwm8Xaq9SPx7TgU/JZdYojIhWgEukr4IFKDJVTmB0Wpo+8mZBKABKDMKphd22zROmBTm1vI5ftZ2MEO6sykukLveixlfBK4MD695JbT0Ny3Lf1jd9mtHlJ2JdymrsP43gkUHpKFjleMlGPWaJdc2dAWATOU535CzejXD6rp/XaAEFi60Ha2M0vko9tG2pbe4x5dkDyJ8EzNZ8kZrnvyobgB3l7dEvav4vLgacp9/q/CkNhD0fWOFyKMrXkzSAOdmU8NrH1JzDQJrtIPa5goFilaqCHFit5TkOBmLBKEuuxioqqGJDxidbin7/3DNZCDD8SGsAFxbVFzv1ZIKeY8JJfjC6uPryvYB27sfadoKysdANn+xyyBiXl4gJQTt0ZNIiroKxwlNt9Y4WqpQd/09Za0u5DCBwKwyalQEMlgVXOQQKHsv9am+/2pXq/lGY1+dZRUP7zeBS1DdYAjiMZTAi17PcmdGKBZbnaMfLr4d5Q7FoLDuCxo98lbyMHWl8f9zGaDP/CbD9vuZ2+27ggf2XNZY5eJZ8BvwYuNyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
